### PR TITLE
[Suggestion] autogen libs load and cmake

### PR DESCRIPTION
**Pull request by bararchy**
Please ignore the version changes etc.. 

This is just an idea to play around with

### CODE REVIEW

**Comment by bararchy** [comment]
BTW, to this change we can add static compile of the voidsmfl libs, so after the binary is compile it will never need voidsmfl again

**Comment by bararchy** [comment]
@oprypin Did you gave those changes any thought? 
I've been using this for testing and deployment and it seems to work nicely.

**Comment by oprypin** [comment]
I gave it *thought* but that's it. Any day now...

**Comment by oprypin** [comment]
This is resolved in https://github.com/oprypin/crsfml/commit/3447b59608c6a86585d82c43641dafe378cba034

**Pull request closed without merging**
